/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valen
 */
public class frmCalculadora extends javax.swing.JFrame {
        private boolean punto=true; // define como verdadero el boton punto
        String valor1, valor2, signo, contenido;
        Double resultado;
       
    /**
     * Creates new form frmCalculadora
     */
    public frmCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmostrar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnpunto = new javax.swing.JButton();
        btnex = new javax.swing.JButton();
        btnsumar = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btnmasmenos = new javax.swing.JButton();
        btnrestar = new javax.swing.JButton();
        btndividir = new javax.swing.JButton();
        btnx2 = new javax.swing.JButton();
        btnmultiplicar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btnxy = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn1x = new javax.swing.JButton();
        btnraiz = new javax.swing.JButton();
        btnc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(67, 55, 87));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtmostrar.setBackground(new java.awt.Color(244, 253, 251));
        txtmostrar.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtmostrar.setForeground(new java.awt.Color(15, 31, 73));
        txtmostrar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpunto.setBackground(new java.awt.Color(121, 121, 121));
        btnpunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btnpunto.setText(".");
        btnpunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });
        jPanel1.add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 50));

        btnex.setBackground(new java.awt.Color(127, 127, 127));
        btnex.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        btnex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnex.setText("e^x");
        btnex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexActionPerformed(evt);
            }
        });
        jPanel1.add(btnex, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 50, 50));

        btnsumar.setBackground(new java.awt.Color(121, 121, 121));
        btnsumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnsumar.setText("+");
        btnsumar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumarActionPerformed(evt);
            }
        });
        jPanel1.add(btnsumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 50, 50));

        btnigual.setBackground(new java.awt.Color(121, 121, 121));
        btnigual.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnigual.setForeground(new java.awt.Color(255, 255, 255));
        btnigual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn2.jpeg"))); // NOI18N
        btnigual.setText("=");
        btnigual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });
        jPanel1.add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 50, 50));

        btnmasmenos.setBackground(new java.awt.Color(131, 131, 131));
        btnmasmenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnmasmenos.setText("±");
        btnmasmenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasmenosActionPerformed(evt);
            }
        });
        jPanel1.add(btnmasmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 50, 50));

        btnrestar.setBackground(new java.awt.Color(121, 121, 121));
        btnrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnrestar.setText("-");
        btnrestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 50, 50));

        btndividir.setBackground(new java.awt.Color(121, 121, 121));
        btndividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btndividir.setText("/");
        btndividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndividirActionPerformed(evt);
            }
        });
        jPanel1.add(btndividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 50, 50));

        btnx2.setBackground(new java.awt.Color(127, 127, 127));
        btnx2.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        btnx2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnx2.setText("x^2");
        btnx2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, 50));

        btnmultiplicar.setBackground(new java.awt.Color(121, 121, 121));
        btnmultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnmultiplicar.setText("*");
        btnmultiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 50, 50));

        btnborrar.setBackground(new java.awt.Color(84, 94, 125));
        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnborrar.setText("<-");
        btnborrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 50));

        btnxy.setBackground(new java.awt.Color(127, 127, 127));
        btnxy.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        btnxy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnxy.setText("x^y");
        btnxy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxyActionPerformed(evt);
            }
        });
        jPanel1.add(btnxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 50));

        btn0.setBackground(new java.awt.Color(131, 131, 131));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn0.setText("0");
        btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 50, 50));

        btn1.setBackground(new java.awt.Color(131, 131, 131));
        btn1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btn1.setForeground(new java.awt.Color(53, 59, 69));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn1.setText("1");
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 50));

        btn2.setBackground(new java.awt.Color(131, 131, 131));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn2.setText("2");
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 50, 50));

        btn3.setBackground(new java.awt.Color(131, 131, 131));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn3.setText("3");
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 50, 50));

        btn6.setBackground(new java.awt.Color(131, 131, 131));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn6.setText("6");
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 50, 50));

        btn5.setBackground(new java.awt.Color(131, 131, 131));
        btn5.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btn5.setForeground(new java.awt.Color(53, 59, 69));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn5.setText("5");
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, 50));

        btn4.setBackground(new java.awt.Color(131, 131, 131));
        btn4.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btn4.setForeground(new java.awt.Color(53, 59, 69));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn4.setText("4");
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setRequestFocusEnabled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 50));

        btn7.setBackground(new java.awt.Color(131, 131, 131));
        btn7.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btn7.setForeground(new java.awt.Color(53, 59, 69));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn7.setText("7");
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 50));

        btn8.setBackground(new java.awt.Color(131, 131, 131));
        btn8.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btn8.setForeground(new java.awt.Color(53, 59, 69));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn8.setText("8");
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 50, 50));

        btn9.setBackground(new java.awt.Color(131, 131, 131));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn4.jpeg"))); // NOI18N
        btn9.setText("9");
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 50, 50));

        btn1x.setBackground(new java.awt.Color(127, 127, 127));
        btn1x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btn1x.setText("1/x");
        btn1x.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1xActionPerformed(evt);
            }
        });
        jPanel1.add(btn1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 50));

        btnraiz.setBackground(new java.awt.Color(95, 62, 93));
        btnraiz.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnraiz.setForeground(new java.awt.Color(53, 59, 69));
        btnraiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnraiz.setText("√");
        btnraiz.setHideActionText(true);
        btnraiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizActionPerformed(evt);
            }
        });
        jPanel1.add(btnraiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 50, 50));

        btnc.setBackground(new java.awt.Color(56, 51, 80));
        btnc.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnc.setForeground(new java.awt.Color(53, 59, 69));
        btnc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn1.jpg"))); // NOI18N
        btnc.setText("c");
        btnc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });
        jPanel1.add(btnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 310, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmostrarActionPerformed
    public static String operaciones(String valor1, String valor2, String signo){
        // Proceso de operaciones para aginar en botones mas
            Double resultadocalc=0.0;
            String respuesta;
            if(signo.equals("+")){
                resultadocalc=Double.parseDouble(valor1)+Double.parseDouble(valor2);
            }else if (signo.equals("-")){
                resultadocalc=Double.parseDouble(valor1)-Double.parseDouble(valor2);
            }else if (signo.equals("*")){
                resultadocalc=Double.parseDouble(valor1)*Double.parseDouble(valor2);
            }else if (signo.equals("/")){
                resultadocalc=Double.parseDouble(valor1)/Double.parseDouble(valor2);
            }else if (signo.equals("x^y")){
                resultadocalc=Math.pow(Double.parseDouble(valor1), (Double.parseDouble(valor2)));
            }
            respuesta=resultadocalc.toString();
            return respuesta;
        }
    private void btnmasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasmenosActionPerformed
        // Realiza la operacion mas menos:
        contenido=txtmostrar.getText();
        if(contenido.length()>0){
            // multiplica -1 para convertir un numero positivo en negativo
            resultado=(-1)*Double.parseDouble(contenido);
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnmasmenosActionPerformed

    private void btnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizActionPerformed
        // Permite Realizar la operacion de raiz
        if(contenido.length()>0){
            resultado=Math.sqrt(Double.parseDouble(contenido));
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnraizActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
       //  Muestra el numero 7 como texto al seleccionar al boton 7
        txtmostrar.setText(txtmostrar.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        //  Muestra el numero 4 como texto al seleccionar al boton 4
        txtmostrar.setText(txtmostrar.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // Muestra el numero 1 como texto al seleccionar al boton 1
        txtmostrar.setText(txtmostrar.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        //  Muestra el numero 0 como texto al seleccionar al boton 0
        txtmostrar.setText(txtmostrar.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1xActionPerformed
        // Asinga la operacion 1/x
        if (contenido.length()>0){
            resultado=1/(Double.parseDouble(contenido));
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btn1xActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        //  Muestra el numero 8 como texto al seleccionar al boton 8
        txtmostrar.setText(txtmostrar.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        //  Muestra el numero 5 como texto al seleccionar al boton 5
        txtmostrar.setText(txtmostrar.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        //  Muestra el numero 2 como texto al seleccionar al boton 2
        txtmostrar.setText(txtmostrar.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        // Asigna la operacion x^2
        contenido=txtmostrar.getText();
        if(contenido.length()>0){
            resultado=Math.pow(Double.parseDouble(contenido),2);
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnx2ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        //  Muestra el numero 9 como texto al seleccionar al boton 9
        txtmostrar.setText(txtmostrar.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       //  Muestra el numero 6 como texto al seleccionar al boton 6
        txtmostrar.setText(txtmostrar.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        //  Muestra el numero 3 como texto al seleccionar al boton 3
        txtmostrar.setText(txtmostrar.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
        //Muestra el signo punto como texto al seleccionar el boton
        contenido=txtmostrar.getText();
        if(contenido.length()<=0){
            //  Muestra el numero 0 como texto al seleccionar al boton 0
        txtmostrar.setText(txtmostrar.getText()+"0.");
        }else
            // lee los puntos existentes y limita a solo colocar uno
            if(txtmostrar.getText().contains(".")){   
            }else{
                txtmostrar.setText(txtmostrar.getText()+".");
                punto=false;
            }
    }//GEN-LAST:event_btnpuntoActionPerformed

    private void btnxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxyActionPerformed
        // Asigna la operacion
         if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            signo="x^y";
            txtmostrar.setText("");
        }
    }//GEN-LAST:event_btnxyActionPerformed

    private void btnsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumarActionPerformed
        // Asigna la operacion de sumar
        if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            signo="+";
            txtmostrar.setText("");
        }
    }//GEN-LAST:event_btnsumarActionPerformed

    private void btnrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestarActionPerformed
        // Asigna la operacion de restar
         if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            signo="-";
            txtmostrar.setText("");
        }
    }//GEN-LAST:event_btnrestarActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        // Agina el resultado en el tablero de texto
        String resultadototal;
        valor2=txtmostrar.getText();
         if(!valor2.equals("")){
            resultadototal=operaciones(valor1, valor2, signo);
            txtmostrar.setText(resultadototal);
        }
    }//GEN-LAST:event_btnigualActionPerformed

    private void btnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexActionPerformed
        // Asigna la operacion e^x
        if(contenido.length()>0){
            resultado=Math.exp(Double.parseDouble(contenido));
            txtmostrar.setText(resultado.toString());
        }                                     
    }//GEN-LAST:event_btnexActionPerformed

    private void btnmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicarActionPerformed
        // Asigna la operacion de multiplicad
         if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            signo="*";
            txtmostrar.setText("");
        }
    }//GEN-LAST:event_btnmultiplicarActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        //  Muestra en blanco la barra de texto al seleccionar al boton c
        txtmostrar.setText("");
    }//GEN-LAST:event_btncActionPerformed

    private void btndividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndividirActionPerformed
       // Asigna la operacion de multiplicar
        if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            signo="/";
            txtmostrar.setText("");
        }
    }//GEN-LAST:event_btndividirActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // Asigna la funcion de borrar al boton (de uno en uno)
        contenido=txtmostrar.getText();
        if (contenido.length()>0);
        contenido=contenido.substring(0, contenido.length()-1);
        txtmostrar.setText(contenido);
    }//GEN-LAST:event_btnborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1x;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btndividir;
    private javax.swing.JButton btnex;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnmasmenos;
    private javax.swing.JButton btnmultiplicar;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnraiz;
    private javax.swing.JButton btnrestar;
    private javax.swing.JButton btnsumar;
    private javax.swing.JButton btnx2;
    private javax.swing.JButton btnxy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtmostrar;
    // End of variables declaration//GEN-END:variables
}
